use crate::codegen::types_generator::{
    generate_conditional_diff_params, generate_conditional_diff_struct,
    generate_input_params_with_names, generate_multiunzip_input_struct, generate_multiunzip_param,
    generate_result_struct_with_name, generate_return_type, generate_structured_params_signature,
    generate_structured_params_struct, strip_input_suffix,
};
use crate::query_definition::{ExpectedResult, QueryDefinition, TelemetryLevel};
use crate::query_definition_rt::QueryDefinitionRuntime;
use crate::rust_type::{InputParam, OutputColumn};
use crate::types_extractor::{parse_parameter_names_from_sql, QueryTypeInfo};
use crate::utils::{to_pascal_case, to_snake_case};
use anyhow::Result;

pub fn generate_root_module(modules: &Vec<String>, source_hash: u64) -> String {
    let mut mod_content = String::new();

    // Add hash comment at the top for consistency with build-time generation
    mod_content.push_str(&format!("// AUTOMODEL_HASH: {}\n", source_hash));
    mod_content
        .push_str("// This file was automatically generated by AutoModel. Do not edit manually.\n");
    mod_content.push_str("// @generated\n\n");

    let mut mod_declarations = Vec::new();
    for module in modules {
        mod_declarations.push(format!("pub mod {};", module));
    }

    // Add module declarations first
    if !mod_declarations.is_empty() {
        for declaration in mod_declarations {
            mod_content.push_str(&declaration);
            mod_content.push('\n');
        }
        mod_content.push('\n');
    }

    // Add generic Error type
    mod_content.push_str(&generate_generic_error_type());

    mod_content
}

/// Generate the generic Error<C> type for mod.rs
pub fn generate_generic_error_type() -> String {
    r#"#[derive(Debug, Clone)]
pub struct ErrorConstraintInfo {
    /// Name of the violated constraint
    pub constraint_name: String,
    pub table_name: String,
    #[allow(unused)]
    pub kind: ErrorConstraintKind,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ErrorConstraintKind {
    UniqueViolation,
    ForeignKeyViolation,
    NotNullViolation,
    CheckViolation,
    Other,
}

impl From<sqlx::error::ErrorKind> for ErrorConstraintKind {
    fn from(kind: sqlx::error::ErrorKind) -> Self {
        match kind {
            sqlx::error::ErrorKind::UniqueViolation => Self::UniqueViolation,
            sqlx::error::ErrorKind::ForeignKeyViolation => Self::ForeignKeyViolation,
            sqlx::error::ErrorKind::NotNullViolation => Self::NotNullViolation,
            sqlx::error::ErrorKind::CheckViolation => Self::CheckViolation,
            _ => Self::Other,
        }
    }
}

/// Generic error type
#[derive(Debug)]
pub enum Error<C: TryFrom<ErrorConstraintInfo>> {
    /// Catches the cases when a mutation query violates a constraint
    /// Type C would be an enum specific to each query.
    /// It would enumerate variants in pascal case for each constraint that can be violated.
    /// The list of constaints is inferred automatically by the automodel based on the table schema
    /// involved in the query.
    /// The Option<C> is None when the constraint name is not recognized (unknown constraint).
    ConstraintViolation(Option<C>, ErrorConstraintInfo),

    /// Row not found error
    RowNotFound,
    
    /// System under stress, timeout
    PoolTimeout,

    InternalError(String, sqlx::Error),
}

impl<C: TryFrom<ErrorConstraintInfo>> From<sqlx::Error> for Error<C> {
    fn from(error: sqlx::Error) -> Self {
        match &error {
            sqlx::Error::RowNotFound => Self::RowNotFound,
            sqlx::Error::ColumnNotFound(col) => {
                Self::InternalError(format!("Column not found: {}", col), error)
            }
            sqlx::Error::Database(db_err) => {
                // Extract constraint name and table from error
                let constraint_name = db_err.constraint().unwrap_or("").to_string();
                let table_name = db_err.table().unwrap_or("").to_string();
                let kind = db_err.kind();

                let violation = ErrorConstraintInfo {
                    constraint_name,
                    table_name,
                    kind: kind.into(),
                };
                Self::ConstraintViolation(violation.clone().try_into().ok(), violation)
            }
            sqlx::Error::Configuration(_) => {
                Self::InternalError("Configuration error".to_string(), error)
            }
            sqlx::Error::InvalidArgument(_) => {
                Self::InternalError("Invalid argument".to_string(), error)
            }
            sqlx::Error::Io(_) => Self::InternalError("IO error".to_string(), error),
            sqlx::Error::Tls(_) => Self::InternalError("TLS error".to_string(), error),
            sqlx::Error::Protocol(_) => Self::InternalError("Protocol error".to_string(), error),
            sqlx::Error::TypeNotFound { type_name } => {
                Self::InternalError(format!("Type not found: {}", type_name), error)
            }
            sqlx::Error::ColumnIndexOutOfBounds { index, len } => Self::InternalError(
                format!("Column index out of bounds: index {}, len {}", index, len),
                error,
            ),
            sqlx::Error::ColumnDecode { index, source } => Self::InternalError(
                format!("Column decode error at index {}: {}", index, source),
                error,
            ),
            sqlx::Error::Encode(_) => Self::InternalError("Encode error".to_string(), error),
            sqlx::Error::Decode(_) => Self::InternalError("Decode error".to_string(), error),
            sqlx::Error::AnyDriverError(_) => {
                Self::InternalError("Driver error".to_string(), error)
            }
            sqlx::Error::PoolTimedOut => Self::PoolTimeout,
            sqlx::Error::PoolClosed => Self::InternalError("Pool closed".to_string(), error),
            sqlx::Error::WorkerCrashed => Self::InternalError("Worker crashed".to_string(), error),
            sqlx::Error::Migrate(_) => Self::InternalError("Migration error".to_string(), error),
            sqlx::Error::InvalidSavePointStatement => Self::InternalError(
                "Invalid save point statement".to_string(),
                error,
            ),
            sqlx::Error::BeginFailed => Self::InternalError("Begin failed".to_string(), error),
            _ => Self::InternalError("Unknown sqlx error".to_string(), error),
        }
    }
}

impl<C> std::fmt::Display for Error<C>
where
    C: std::fmt::Debug + TryFrom<ErrorConstraintInfo>,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::ConstraintViolation(constraint, info) => {
                if let Some(c) = constraint {
                    write!(f, "Constraint violation: {:#?}", c)
                } else {
                    write!(f, "Unknown constraint violation: {} on table {}", info.constraint_name, info.table_name)
                }
            }
            Error::RowNotFound => write!(f, "Row not found"),
            Error::PoolTimeout => write!(f, "Pool timeout"),
            Error::InternalError(msg, err) => {
                write!(f, "Internal error: {}, caused by: {}", msg, err)
            }
        }
    }
}

impl<C> std::error::Error for Error<C>
where
    C: std::fmt::Debug + TryFrom<ErrorConstraintInfo>,
{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Error::InternalError(_, err) => Some(err),
            _ => None,
        }
    }
}

/// Generic error type for read-only queries
#[derive(Debug)]
pub enum ErrorReadOnly {
    /// Row not found error
    RowNotFound,

    /// System under stress, timeout
    PoolTimeout,

    InternalError(String, sqlx::Error),
}

impl From<sqlx::Error> for ErrorReadOnly {
    fn from(error: sqlx::Error) -> Self {
        Error::<ErrorConstraintInfo>::from(error).into()
    }
}

impl Into<Error<ErrorConstraintInfo>> for ErrorReadOnly {
    fn into(self) -> Error<ErrorConstraintInfo> {
        match self {
            ErrorReadOnly::RowNotFound => Error::RowNotFound,
            ErrorReadOnly::PoolTimeout => Error::PoolTimeout,
            ErrorReadOnly::InternalError(msg, err) => Error::InternalError(msg, err),
        }
    }
}

impl From<Error<ErrorConstraintInfo>> for ErrorReadOnly {
    fn from(error: Error<ErrorConstraintInfo>) -> Self {
        match error {
            Error::RowNotFound => Self::RowNotFound,
            Error::PoolTimeout => Self::PoolTimeout,
            Error::InternalError(msg, err) => Self::InternalError(msg, err),
            Error::ConstraintViolation(c, info) => Self::InternalError(
                "Constraint violation in read-only query".to_string(),
                sqlx::Error::Protocol(format!(
                    "Constraint violation in read-only query: constraint={}, table={}, parsed={:?}",
                    info.constraint_name, info.table_name, c
                )),
            ),
        }
    }
}

impl std::fmt::Display for ErrorReadOnly {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ErrorReadOnly::RowNotFound => write!(f, "Row not found"),
            ErrorReadOnly::PoolTimeout => write!(f, "Pool timeout"),
            ErrorReadOnly::InternalError(msg, err) => {
                write!(f, "Internal error: {}, caused by: {}", msg, err)
            }
        }
    }
}

impl std::error::Error for ErrorReadOnly {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::InternalError(_, err) => Some(err),
            _ => None,
        }
    }
}

"#
    .to_string()
}

/// Generate per-query constraint enum with TryFrom<ErrorConstraintInfo> implementation
pub fn generate_query_constraint_enum(
    enum_name: &str,
    constraints: &[crate::types_extractor::ConstraintInfo],
    custom_derives: &[String],
) -> String {
    use std::collections::HashSet;

    let mut code = String::new();

    // Deduplicate constraints by name
    let mut seen_constraints: HashSet<String> = HashSet::new();
    let mut unique_constraints = Vec::new();
    for constraint in constraints {
        if !seen_constraints.contains(&constraint.name) {
            seen_constraints.insert(constraint.name.clone());
            unique_constraints.push(constraint);
        }
    }

    code.push_str(&format!(
        "/// Constraint violations specific to this query\n"
    ));

    // Build derive attribute with Debug as default plus custom derives
    let mut all_derives = vec!["Debug".to_string()];
    all_derives.extend(custom_derives.iter().cloned());

    // Remove duplicates while preserving order
    let mut seen = HashSet::new();
    all_derives.retain(|d| seen.insert(d.clone()));

    code.push_str(&format!("#[derive({})]\n", all_derives.join(", ")));
    code.push_str(&format!("pub enum {} {{\n", enum_name));

    // Generate a variant for each unique constraint
    for constraint in &unique_constraints {
        let variant_name = to_pascal_case(&constraint.name);
        code.push_str(&format!(
            "    /// Constraint: {} on table {}\n",
            constraint.name, constraint.table_name
        ));
        code.push_str(&format!("    {},\n", variant_name));
    }

    code.push_str("}\n\n");

    // Generate TryFrom<ErrorConstraintInfo> implementation
    code.push_str(&format!(
        "impl TryFrom<super::ErrorConstraintInfo> for {} {{\n",
        enum_name
    ));
    code.push_str("    type Error = ();\n\n");
    code.push_str(
        "    fn try_from(info: super::ErrorConstraintInfo) -> Result<Self, Self::Error> {\n",
    );
    code.push_str("        match info.constraint_name.as_str() {\n");

    for constraint in &unique_constraints {
        let variant_name = to_pascal_case(&constraint.name);
        code.push_str(&format!(
            "            \"{}\" => Ok(Self::{}),\n",
            constraint.name, variant_name
        ));
    }

    code.push_str("            _ => Err(()),\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}

/// Remove statistics from EXPLAIN plan lines to make output stable
/// Removes patterns like: (cost=X..Y rows=Z width=W)
fn remove_plan_statistics(line: &str) -> String {
    use regex::Regex;
    use std::sync::OnceLock;

    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        // Match patterns like (cost=10000000000.00..10000000003.74 rows=59 width=64)
        // The pattern handles:
        // - Optional cost=X..Y
        // - Optional rows=Z
        // - Optional width=W
        // All enclosed in parentheses with spaces
        Regex::new(r"\s*\((?:cost=[\d.]+\.\.[\d.]+\s*)?(?:rows=\d+\s*)?(?:width=\d+\s*)?\)")
            .unwrap()
    });

    re.replace_all(line, "").trim_end().to_string()
}

/// Generate tracing::instrument attribute for a function
fn generate_tracing_attribute(query: &QueryDefinition, param_names: &[String]) -> String {
    use std::collections::HashSet;

    let telemetry_level = query.telemetry.level;
    if telemetry_level == TelemetryLevel::None {
        return String::new();
    }

    let mut attributes = Vec::new();

    // No need for explicit span name - tracing::instrument will use the function name automatically

    // Add instrumentation level
    let level = match telemetry_level {
        TelemetryLevel::Info => "info",
        TelemetryLevel::Debug => "debug",
        TelemetryLevel::Trace => "trace",
        TelemetryLevel::None => unreachable!(),
    };
    attributes.push(format!("level = \"{}\"", level));

    // Determine parameter skipping strategy
    let mut skip_params = HashSet::new();
    skip_params.insert("executor".to_string());

    // Parameter inclusion logic (independent of telemetry level)
    if let Some(include_params) = &query.telemetry.include_params {
        if include_params.is_empty() {
            // Empty include_params list means skip all parameters
            skip_params.extend(param_names.iter().cloned());
        } else {
            let included: Vec<String> = include_params
                .iter()
                .filter(|param| param_names.contains(param))
                .cloned()
                .collect();

            if !included.is_empty() {
                // Skip parameters not in the include list
                for param in param_names {
                    if !included.contains(param) {
                        skip_params.insert(param.clone());
                    }
                }
            } else {
                // No valid included parameters, skip all
                skip_params.extend(param_names.iter().cloned());
            }
        }
    } else {
        // No include_params specified, skip all parameters
        skip_params.extend(param_names.iter().cloned());
    }

    // Check if we should use skip_all (all params including query params are skipped)
    let total_params = param_names.len() + 1; // +1 for executor
    let should_use_skip_all = param_names.len() > 0 && skip_params.len() == total_params;

    // Generate skip attribute
    if should_use_skip_all {
        attributes.push("skip_all".to_string());
    } else if skip_params.len() > 1 {
        // More than just executor
        let mut skip_vec: Vec<_> = skip_params.into_iter().collect();
        skip_vec.sort(); // Sort for consistent output
        attributes.push(format!("skip({})", skip_vec.join(", ")));
    } else {
        attributes.push("skip_all".to_string());
    }

    // Determine whether to include SQL based on configuration (default false)
    let should_include_sql = query.telemetry.include_sql;
    if should_include_sql {
        let escaped_sql = query
            .sql
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n");
        attributes.push(format!("fields(sql = \"{}\")", escaped_sql));
    }

    format!("#[tracing::instrument({})]\n", attributes.join(", "))
}

/// Generate an indented raw string literal with proper formatting
fn generate_indented_raw_string_literal(sql: &str) -> String {
    // Find a delimiter that doesn't appear in the SQL. A raw string
    // r{#*}"..."{#*} is terminated by a double-quote followed by the same
    // number of '#'. So the unsafe sequence to avoid is `"` + delimiter.
    let mut delimiter_count = 0;
    let delimiter = loop {
        let delimiter = "#".repeat(delimiter_count);
        let pattern = format!("\"{}", delimiter);
        if !sql.contains(&pattern) {
            break delimiter;
        }
        delimiter_count += 1;
    };

    // Add proper indentation to each line of SQL
    let indented_sql = sql
        .lines()
        .enumerate()
        .map(|(i, line)| {
            if i == 0 {
                line.to_string() // First line doesn't need extra indentation
            } else {
                format!("        {}", line) // Subsequent lines get 8 spaces of indentation
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "        r{delimiter}\"{indented_sql}\"{delimiter}",
        delimiter = delimiter,
        indented_sql = indented_sql
    )
}

/// Generate Rust function code for a SQL query without enum definitions
/// (assumes enums are already defined elsewhere in the module)
pub fn generate_function_code_without_enums(
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    emitted_struct_names: &mut std::collections::HashSet<String>,
    constraints: &[crate::types_extractor::ConstraintInfo],
    performance_analysis: &Option<crate::query_definition_rt::PerformanceAnalysis>,
    defaults: &crate::DefaultsConfig,
) -> Result<String> {
    let mut code = String::new();

    // Generate per-query constraint enum if there are constraints
    let constraint_enum_name = if !constraints.is_empty() {
        // Determine the enum name from error_type config or use default
        let enum_name = if let Some(ref custom_name) = query.error_type {
            custom_name.to_string()
        } else {
            format!("{}Constraints", to_pascal_case(&query.name))
        };

        // Only generate the enum if it hasn't been emitted yet
        if !emitted_struct_names.contains(&enum_name) {
            code.push_str(&generate_query_constraint_enum(
                &enum_name,
                constraints,
                &query.error_type_derives,
            ));
            code.push('\n');
            emitted_struct_names.insert(enum_name.clone());
        }

        Some(enum_name)
    } else {
        None
    };

    // Extract clean parameter names directly from the SQL for function signature
    let original_param_names = parse_parameter_names_from_sql(&query.sql);
    let clean_param_names: Vec<String> = original_param_names
        .iter()
        .map(|name| strip_input_suffix(name))
        .collect();

    let use_multiunzip = query.multiunzip;

    // Determine if conditions_type is enabled and get the struct name override
    let (use_conditional_diff, diff_struct_name_override) = match &query.conditions_type {
        crate::query_definition::ConditionsType::Enabled(true) => (true, None),
        crate::query_definition::ConditionsType::Named(name) => (true, Some(name.as_str())),
        _ => (false, None),
    };

    // Determine if parameters_type is enabled and get the struct name
    let (use_structured_params, struct_name_override) = match &query.parameters_type {
        crate::query_definition::ParametersType::Enabled(true) if !use_conditional_diff => {
            (true, None)
        }
        crate::query_definition::ParametersType::Named(name) if !use_conditional_diff => {
            (true, Some(name.as_str()))
        }
        _ => (false, None),
    };

    // Generate input struct for multiunzip if needed
    if use_multiunzip {
        let struct_name = format!("{}Record", to_pascal_case(&query.name));
        if !emitted_struct_names.contains(&struct_name) {
            if let Some(input_struct) = generate_multiunzip_input_struct(
                &query.name,
                &clean_param_names,
                &type_info.input_types,
                &query.parameters_type_derives,
            ) {
                code.push_str(&input_struct);
                code.push('\n');
                emitted_struct_names.insert(struct_name);
            }
        }
    }

    // Generate diff struct for conditions_type if needed
    if use_conditional_diff && type_info.parsed_sql.is_some() {
        let struct_name = if let Some(override_name) = diff_struct_name_override {
            override_name.to_string()
        } else {
            format!("{}Params", to_pascal_case(&query.name))
        };

        if !emitted_struct_names.contains(&struct_name) {
            if let Some(diff_struct) = generate_conditional_diff_struct(
                &struct_name,
                &original_param_names,
                &type_info.input_types,
                &query.conditions_type_derives,
            ) {
                code.push_str(&diff_struct);
                code.push('\n');
                emitted_struct_names.insert(struct_name);
            }
        }
    }

    // Generate struct for parameters_type if needed (but not for conditions_type)
    if use_structured_params {
        let struct_name = if let Some(override_name) = struct_name_override {
            override_name.to_string()
        } else {
            format!("{}Params", to_pascal_case(&query.name))
        };

        if !emitted_struct_names.contains(&struct_name) {
            if let Some(params_struct) = generate_structured_params_struct(
                struct_name_override.unwrap_or(&query.name),
                &clean_param_names,
                &type_info.input_types,
                &query.parameters_type_derives,
            ) {
                code.push_str(&params_struct);
                code.push('\n');
                emitted_struct_names.insert(struct_name);
            }
        }
    }

    // Generate result struct if needed (but no enums)
    // Generate if: multiple columns OR single column with explicit return_type configured
    let should_generate_struct = type_info.output_types.len() > 1 || query.return_type.is_some();

    if should_generate_struct {
        let result_struct_name = if let Some(ref custom_name) = query.return_type {
            custom_name.to_string()
        } else {
            format!("{}Item", to_pascal_case(&query.name))
        };

        if !emitted_struct_names.contains(&result_struct_name) {
            if let Some(struct_def) = generate_result_struct_with_name(
                &result_struct_name,
                &type_info.output_types,
                &query.return_type_derives,
                emitted_struct_names,
            ) {
                code.push_str(&struct_def);
                code.push('\n');
                emitted_struct_names.insert(result_struct_name);
            }
        }
    }

    // Generate the selector enum(s) for the query's choice group(s).
    if !query.choice_groups.is_empty() {
        code.push_str(&generate_choice_group_enum_defs(query, type_info));
        for group in &query.choice_groups {
            emitted_struct_names.insert(choice_group_enum_name(&query.name, &group.selector));
        }
    }

    // Generate function documentation
    if let Some(description) = &query.description {
        code.push_str(&format!("/// {}\n", description));
    }

    // Add query plan as documentation comments if available
    if let Some(perf_analysis) = performance_analysis {
        if let Some(plan) = &perf_analysis.query_plan {
            code.push_str("///\n");
            code.push_str("/// Query Plan:\n");
            for line in plan.lines() {
                // Remove cost estimates, row counts, and width from the plan to avoid instability
                // These values change between runs and make the generated code unstable
                let cleaned_line = remove_plan_statistics(line);
                code.push_str(&format!("/// {}\n", cleaned_line));
            }
        }
    }

    let tracing_attribute = if !query.choice_groups.is_empty() {
        // Variant fields are not function arguments; only skip real args.
        let arg_names = choice_group_arg_names(query, type_info);
        generate_tracing_attribute(query, &arg_names)
    } else {
        generate_tracing_attribute(query, &clean_param_names)
    };
    code.push_str(&tracing_attribute);

    let input_params = if !query.choice_groups.is_empty() {
        // Mutually-exclusive choice group: selector enum + non-grouped args.
        generate_choice_group_signature(query, type_info)
    } else if use_multiunzip {
        // For multiunzip, generate a single Vec<StructName> parameter
        generate_multiunzip_param(&query.name, "items")
    } else if use_conditional_diff && type_info.parsed_sql.is_some() {
        // For conditions_type, generate old and new struct parameters
        generate_conditional_diff_params(
            &query.name,
            &original_param_names,
            &type_info.input_types,
            diff_struct_name_override.as_deref(),
        )
    } else if use_structured_params {
        // For parameters_type, generate a single struct parameter
        generate_structured_params_signature(&query.name, struct_name_override.as_deref())
    } else {
        generate_input_params_with_names(&type_info.input_types, &clean_param_names)
    };

    let base_return_type = if query.return_type.is_some() || type_info.output_types.len() > 1 {
        // Use struct name if: explicit return_type configured OR multi-column result
        if let Some(ref custom_name) = query.return_type {
            custom_name.to_string()
        } else {
            format!("{}Item", to_pascal_case(&query.name))
        }
    } else {
        // Single column result without explicit return_type - use direct type
        generate_return_type(type_info.output_types.first())
    };

    // Generate function signature
    let params_str = if input_params.is_empty() {
        "executor: impl sqlx::Executor<'_, Database = sqlx::Postgres>".to_string()
    } else {
        format!(
            "executor: impl sqlx::Executor<'_, Database = sqlx::Postgres>, {}",
            input_params
        )
    };

    let return_type = if type_info.output_types.is_empty() {
        let error_type = if let Some(ref enum_name) = constraint_enum_name {
            format!("super::Error<{}>", enum_name)
        } else {
            "super::ErrorReadOnly".to_string()
        };
        format!("Result<(), {}>", error_type)
    } else {
        match query.expect {
            ExpectedResult::ExactlyOne => {
                let error_type = if let Some(ref enum_name) = constraint_enum_name {
                    format!("super::Error<{}>", enum_name)
                } else {
                    "super::ErrorReadOnly".to_string()
                };
                format!("Result<{}, {}>", base_return_type, error_type)
            }
            ExpectedResult::PossibleOne => {
                let error_type = if let Some(ref enum_name) = constraint_enum_name {
                    format!("super::Error<{}>", enum_name)
                } else {
                    "super::ErrorReadOnly".to_string()
                };
                format!("Result<Option<{}>, {}>", base_return_type, error_type)
            }
            ExpectedResult::AtLeastOne | ExpectedResult::Multiple => {
                let error_type = if let Some(ref enum_name) = constraint_enum_name {
                    format!("super::Error<{}>", enum_name)
                } else {
                    "super::ErrorReadOnly".to_string()
                };
                format!("Result<Vec<{}>, {}>", base_return_type, error_type)
            }
        }
    };

    code.push_str(&format!(
        "pub async fn {}({}) -> {} {{\n",
        query.name, params_str, return_type
    ));

    // Generate function body
    let function_body = if !query.choice_groups.is_empty() {
        let mut body = String::new();
        let parsed_sql = type_info.parsed_sql.as_ref().ok_or_else(|| {
            anyhow::anyhow!(
                "internal error: choice-group query '{}' has no parsed conditional SQL",
                query.name
            )
        })?;
        generate_choice_group_function_body(
            &mut body,
            query,
            type_info,
            parsed_sql,
            &base_return_type,
        )?;
        body
    } else {
        generate_function_body(query, type_info, &base_return_type, defaults)?
    };
    code.push_str(&function_body);

    code.push_str("}\n");

    Ok(code)
}

/// Generate struct creation code for multi-column results

/// Generate the function body using SQLx
fn generate_function_body(
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    return_type: &str,
    defaults: &crate::DefaultsConfig,
) -> Result<String> {
    let mut body = String::new();

    // Check if this query has conditional blocks
    if let Some(parsed_sql) = &type_info.parsed_sql {
        // Generate dynamic SQL building for conditional queries
        generate_conditional_function_body(
            &mut body,
            query,
            type_info,
            parsed_sql,
            return_type,
            defaults,
        )?;
    } else {
        // Generate standard static SQL
        generate_static_function_body(&mut body, query, type_info, return_type, defaults)?;
    }

    Ok(body)
}

/// Generate function body for static (non-conditional) SQL queries
fn generate_static_function_body(
    body: &mut String,
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    return_type: &str,
    defaults: &crate::DefaultsConfig,
) -> Result<()> {
    let use_multiunzip = query.multiunzip;
    let use_conditional_diff = query.conditions_type.is_enabled();
    let use_structured_params = query.parameters_type.is_enabled() && !use_conditional_diff;
    // Add import for multiunzip based on configuration
    if use_multiunzip {
        match defaults.multiunzip_crate {
            crate::MultiunzipCrate::Itertools => {
                body.push_str("    use itertools::Itertools;\n");
            }
            crate::MultiunzipCrate::ManyUnzip => {
                body.push_str("    use many_unzip::ManyUnzip;\n");
            }
        }
    }

    // Get pre-computed converted SQL and param names from first variant (base query)
    let (converted_sql, param_names, _variant_label) = &query.sql_variants[0];

    // Build the SQLx query with parameter bindings
    let raw_string = generate_indented_raw_string_literal(converted_sql);
    body.push_str(&format!(
        "    let query = sqlx::query(\n{}\n    );\n",
        raw_string
    ));

    // Add parameter bindings using method chaining
    if !type_info.input_types.is_empty() {
        if use_multiunzip {
            // Generate multiunzip pattern with struct field extraction

            // Get clean parameter names for field extraction
            let original_param_names = parse_parameter_names_from_sql(&query.sql);
            let clean_param_names: Vec<String> = original_param_names
                .iter()
                .map(|name| strip_input_suffix(name))
                .collect();

            // Generate the tuple pattern based on number of types
            let num_types = type_info.input_types.len();

            // Validate parameter count against multiunzip limits
            match defaults.multiunzip_crate {
                crate::MultiunzipCrate::Itertools => {
                    if num_types > 12 {
                        return Err(anyhow::anyhow!(
                            "Query '{}' uses multiunzip with {} parameters, but itertools::multiunzip only supports up to 12 parameters.\n\nTo fix this, you have two options:\n1. Configure AutoModel to use many-unzip in your build.rs:\n   multiunzip_crate: automodel::MultiunzipCrate::ManyUnzip\n2. Reduce the number of columns in your batch insert to 12 or fewer",
                            query.name, num_types
                        ));
                    }
                }
                crate::MultiunzipCrate::ManyUnzip => {
                    if num_types > 196 {
                        return Err(anyhow::anyhow!(
                            "Query '{}' uses multiunzip with {} parameters, but many_unzip::ManyUnzip only supports up to 196 parameters.\n\nTo fix this, reduce the number of columns in your batch insert to 196 or fewer.",
                            query.name, num_types
                        ));
                    }
                }
            }

            let tuple_vars: Vec<String> = clean_param_names
                .iter()
                .map(|name| {
                    // Convert to snake_case for consistency
                    to_snake_case(name)
                })
                .collect();
            let tuple_pattern = tuple_vars.join(", ");

            body.push_str(&format!(
                "    let ({}): ({}) =\n",
                tuple_pattern,
                vec!["Vec<_>"; num_types].join(", ")
            ));
            body.push_str("        items\n");
            body.push_str("            .into_iter()\n");

            // Generate the map closure to extract struct fields
            body.push_str(&format!(
                "            .map(|item| ({}))\n",
                tuple_vars
                    .iter()
                    .map(|field| format!("item.{}", field))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));

            // Use the appropriate method name based on the configured crate
            let unzip_method = match defaults.multiunzip_crate {
                crate::MultiunzipCrate::Itertools => "multiunzip",
                crate::MultiunzipCrate::ManyUnzip => "many_unzip",
            };
            body.push_str(&format!("            .{}();\n", unzip_method));

            // Bind each array
            for (i, var) in tuple_vars.iter().enumerate() {
                let rust_type_info = &type_info.input_types[i];

                if rust_type_info.needs_json_wrapper {
                    if rust_type_info.is_optional {
                        // For optional custom types in arrays, each element is Option<T>
                        // Map each element: None stays None, Some(v) becomes Some(to_value(v))
                        body.push_str(&format!(
                            "    let {}_json: Result<Vec<Option<serde_json::Value>>, _> = {}.into_iter().map(|v| v.map(|inner| serde_json::to_value(&inner)).transpose()).collect();\n",
                            var, var
                        ));
                    } else {
                        // For custom types in arrays, we need to serialize each element
                        body.push_str(&format!(
                            "    let {}_json: Result<Vec<serde_json::Value>, _> = {}.into_iter().map(|v| serde_json::to_value(&v)).collect();\n",
                            var, var
                        ));
                    }
                    body.push_str(&format!(
                        "    let query = query.bind({}_json.map_err(|e| sqlx::Error::Encode(Box::new(e)))?);\n",
                        var
                    ));
                } else {
                    // For optional parameters, multiunzip produces Vec<Option<T>>
                    // This is correct for PostgreSQL arrays which support NULL elements
                    // sqlx handles Vec<Option<T>> -> ARRAY[...] with NULLs correctly
                    body.push_str(&format!("    let query = query.bind({});\n", var));
                }
            }
        } else if use_structured_params {
            // For parameters_type, bind from the params struct.
            for (i, name) in param_names.iter().enumerate() {
                let clean_name = if name.ends_with('?') {
                    name.trim_end_matches('?').to_string()
                } else {
                    name.clone()
                };
                emit_static_bind(
                    body,
                    &type_info.input_types[i],
                    &format!("params.{}", clean_name),
                    &clean_name,
                );
            }
        } else if param_names.is_empty() {
            // Fallback to generic param names
            for i in 1..=type_info.input_types.len() {
                body.push_str(&format!("    let query = query.bind(param_{});\n", i));
            }
        } else {
            // Use meaningful parameter names from SQL.
            for (i, name) in param_names.iter().enumerate() {
                let clean_name = strip_input_suffix(name);
                emit_static_bind(body, &type_info.input_types[i], &clean_name, &clean_name);
            }
        }
    }

    generate_query_execution(body, query, type_info, return_type);
    Ok(())
}

// ===== Mutually-exclusive choice groups =====
// A choice group compiles a set of alternative conditional blocks (each tagged
// `#{selector=variant!}` / `?`) into a single generated enum argument, so the
// caller picks exactly one branch and the type system makes any other
// combination unrepresentable.

/// PascalCase name of the generated selector enum, e.g. `GetUsersSort`.
fn choice_group_enum_name(query_name: &str, selector: &str) -> String {
    format!("{}{}", to_pascal_case(query_name), to_pascal_case(selector))
}

/// Build a map from clean parameter name to its resolved `InputParam`
/// (first occurrence wins). `input_types` is aligned positionally with the
/// source-order parameter names of `query.sql`.
fn choice_group_type_map(
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
) -> std::collections::HashMap<String, InputParam> {
    let clean_names: Vec<String> = parse_parameter_names_from_sql(&query.sql)
        .iter()
        .map(|n| strip_input_suffix(n))
        .collect();
    let mut map = std::collections::HashMap::new();
    for (i, ip) in type_info.input_types.iter().enumerate() {
        if let Some(name) = clean_names.get(i) {
            map.entry(name.clone()).or_insert_with(|| ip.clone());
        }
    }
    map
}

/// Render an input parameter's Rust type honoring `?`/`??` optionality, matching
/// `generate_input_params_with_names`.
fn render_choice_param_type(ip: &InputParam) -> String {
    if ip.is_optional && ip.field.is_nullable {
        format!("Option<Option<{}>>", ip.rust_type())
    } else if ip.field.is_nullable || ip.is_optional {
        format!("Option<{}>", ip.rust_type())
    } else {
        ip.rust_type().to_string()
    }
}

/// The actual function-argument names for a choice-group query, in signature
/// order: non-grouped params (source order), then each group's selector.
/// Variant fields are NOT arguments (they live inside the enum), so they must be
/// excluded from e.g. `#[tracing::instrument(skip(...))]`.
fn choice_group_arg_names(query: &QueryDefinition, type_info: &QueryTypeInfo) -> Vec<String> {
    let type_map = choice_group_type_map(query, type_info);

    let mut selectors: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut grouped: std::collections::HashSet<String> = std::collections::HashSet::new();
    for group in &query.choice_groups {
        selectors.insert(group.selector.clone());
        for v in &group.variants {
            grouped.extend(v.all_params());
        }
    }
    let clean_names: Vec<String> = parse_parameter_names_from_sql(&query.sql)
        .iter()
        .map(|n| strip_input_suffix(n))
        .collect();

    let mut names: Vec<String> = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for name in &clean_names {
        if selectors.contains(name) || grouped.contains(name) {
            continue;
        }
        if seen.insert(name.clone()) && type_map.contains_key(name) {
            names.push(name.clone());
        }
    }
    for group in &query.choice_groups {
        names.push(group.selector.clone());
    }
    names
}

/// Emit the selector enum definition(s) for a query's choice group(s).
fn generate_choice_group_enum_defs(query: &QueryDefinition, type_info: &QueryTypeInfo) -> String {
    let type_map = choice_group_type_map(query, type_info);
    let mut code = String::new();
    for group in &query.choice_groups {
        let enum_name = choice_group_enum_name(&query.name, &group.selector);

        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str(&format!("pub enum {} {{\n", enum_name));
        for variant in &group.variants {
            // Every parameter in this branch is a field: direct params are
            // mandatory (`T`); nested optional-block params (Option B) are
            // `Option<T>` (their presence gates the nested clause at runtime).
            let nested: std::collections::HashSet<String> = variant
                .nested_blocks
                .iter()
                .flat_map(|nb| nb.params.iter().cloned())
                .collect();
            let mut fields: Vec<String> = Vec::new();
            for p in variant.all_params() {
                if fields.contains(&p) {
                    continue;
                }
                fields.push(p);
            }
            let pascal = to_pascal_case(&variant.variant);
            if fields.is_empty() {
                code.push_str(&format!("    {},\n", pascal));
            } else {
                code.push_str(&format!("    {} {{\n", pascal));
                for f in &fields {
                    let base_ty = type_map
                        .get(f)
                        .map(|ip| ip.rust_type().to_string())
                        .unwrap_or_else(|| "String".to_string());
                    let ty = if nested.contains(f) {
                        format!("Option<{}>", base_ty)
                    } else {
                        base_ty
                    };
                    code.push_str(&format!("        {}: {},\n", f, ty));
                }
                code.push_str("    },\n");
            }
        }
        code.push_str("}\n\n");
    }
    code
}

/// Build the function-signature argument list for a choice-group query:
/// non-grouped params (source order), then for each group its selector enum
/// argument.
fn generate_choice_group_signature(query: &QueryDefinition, type_info: &QueryTypeInfo) -> String {
    let type_map = choice_group_type_map(query, type_info);

    // Union of all selector names and all grouped params across every group.
    let mut selectors: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut grouped: std::collections::HashSet<String> = std::collections::HashSet::new();
    for group in &query.choice_groups {
        selectors.insert(group.selector.clone());
        for v in &group.variants {
            grouped.extend(v.all_params());
        }
    }

    let clean_names: Vec<String> = parse_parameter_names_from_sql(&query.sql)
        .iter()
        .map(|n| strip_input_suffix(n))
        .collect();

    let mut parts: Vec<String> = Vec::new();
    let mut seen = std::collections::HashSet::new();

    // Non-grouped params first, in source order.
    for name in &clean_names {
        if selectors.contains(name) || grouped.contains(name) {
            continue;
        }
        if !seen.insert(name.clone()) {
            continue;
        }
        if let Some(ip) = type_map.get(name) {
            parts.push(format!("{}: {}", name, render_choice_param_type(ip)));
        }
    }

    // Per group: selector enum argument.
    for group in &query.choice_groups {
        let enum_name = choice_group_enum_name(&query.name, &group.selector);
        let sel_ty = if group.required {
            enum_name
        } else {
            format!("Option<{}>", enum_name)
        };
        parts.push(format!("{}: {}", group.selector, sel_ty));
    }

    parts.join(", ")
}

/// Recursively emit `qb` push / push_bind statements for the tokens of one
/// conditional block body (already tokenized from directive-stripped
/// `sql_content`).
///
/// `grouped_top` is true when these tokens form the immediate body of a chosen
/// choice-group branch: their direct parameters are mandatory enum fields that
/// have already been destructured as references and are bound as-is. Otherwise
/// (additive blocks and any nested `#[...]` block) parameters are `Option`-typed
/// — plain `Option<T>` arguments or destructured `Option` enum fields — and are
/// unwrapped via `.as_ref().unwrap()`. Nested blocks are always gated by their
/// first parameter's `is_some()` and emit their bodies in non-`grouped_top`
/// mode. All values flow through `push_bind`, never string interpolation.
fn emit_choice_group_block_tokens(
    body: &mut String,
    tokens: &[SqlToken],
    indent: &str,
    grouped_top: bool,
    all_params: &[String],
    type_info: &QueryTypeInfo,
) {
    for token in tokens {
        match token {
            SqlToken::Lit(s) => {
                if !s.is_empty() {
                    body.push_str(&format!("{}qb.push({});\n", indent, raw_string_literal(s)));
                }
            }
            SqlToken::Param(name) => {
                let clean = name.trim_end_matches('?');
                let owner = if grouped_top {
                    clean.to_string()
                } else {
                    format!("{}.as_ref().unwrap()", clean)
                };
                if let Some(ti) = find_input_type(all_params, type_info, clean) {
                    emit_push_bind(body, indent, ti, &owner, true, clean);
                }
            }
            SqlToken::Block { inner, params } => {
                if params.is_empty() {
                    emit_choice_group_block_tokens(
                        body, inner, indent, false, all_params, type_info,
                    );
                    continue;
                }
                let gate = params[0].trim_end_matches('?');
                body.push_str(&format!("{}if {}.is_some() {{\n", indent, gate));
                let inner_indent = format!("{}    ", indent);
                emit_choice_group_block_tokens(
                    body,
                    inner,
                    &inner_indent,
                    false,
                    all_params,
                    type_info,
                );
                body.push_str(&format!("{}}}\n", indent));
            }
        }
    }
}

/// Generate the function body for any choice-group query.
///
/// Handles the full range of choice-group shapes: a single group, multiple
/// independent groups, variants spanning several conditional blocks, nested
/// optional (`#[...]`) blocks inside a branch, and additive (ungrouped)
/// conditional blocks mixed in.
///
/// The base SQL is tokenized and emitted through a `sqlx::QueryBuilder`:
/// additive blocks become `if <param>.is_some()` guards, and each choice-group
/// block becomes an `if let <Enum>::<Variant> { .. } = &<selector>` guard that
/// pushes only the selected branch. Because `push_bind` assigns `$N`
/// placeholders in push (source) order, no sentinelization, renumbering or
/// `included_params` bookkeeping is required.
fn generate_choice_group_function_body(
    body: &mut String,
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    parsed_sql: &crate::types_extractor::ParsedSql,
    return_type: &str,
) -> Result<()> {
    use crate::types_extractor::parse_parameter_names_from_sql;

    if query.conditions_type.is_enabled() || query.parameters_type.is_enabled() {
        anyhow::bail!(
            "Query '{}' combines a choice group with conditions_type/parameters_type, which is \
             not supported. Use plain named parameters with the choice group.",
            query.name
        );
    }

    let all_params = parse_parameter_names_from_sql(&query.sql);

    // Map each top-level conditional-block index to its owning (group, variant).
    let mut block_owner: std::collections::HashMap<usize, (usize, usize)> =
        std::collections::HashMap::new();
    for (gi, group) in query.choice_groups.iter().enumerate() {
        for (vi, variant) in group.variants.iter().enumerate() {
            for &bi in &variant.block_indices {
                block_owner.insert(bi, (gi, vi));
            }
        }
    }

    body.push_str("    let mut qb = sqlx::QueryBuilder::<sqlx::Postgres>::new(\"\");\n");

    let tokens = tokenize_base_sql(&parsed_sql.base_sql);
    let mut block_idx = 0usize;
    for token in &tokens {
        match token {
            SqlToken::Lit(s) => {
                if !s.is_empty() {
                    body.push_str(&format!("    qb.push({});\n", raw_string_literal(s)));
                }
            }
            SqlToken::Param(name) => {
                // Top-level (base) parameter: always present.
                let clean = name.trim_end_matches('?');
                if let Some(ti) = find_input_type(&all_params, type_info, clean) {
                    emit_push_bind(body, "    ", ti, clean, false, clean);
                }
            }
            SqlToken::Block { .. } => {
                let i = block_idx;
                block_idx += 1;
                let block = &parsed_sql.conditional_blocks[i];
                // Use the directive-stripped body so the choice-group selector
                // markers (`#{sort=asc!}`) never appear in the emitted SQL.
                let inner = tokenize_base_sql(&block.sql_content);

                if let Some(&(gi, vi)) = block_owner.get(&i) {
                    // Grouped block: emit under an `if let` for its branch.
                    let group = &query.choice_groups[gi];
                    let variant = &group.variants[vi];
                    let enum_name = choice_group_enum_name(&query.name, &group.selector);
                    let pascal = to_pascal_case(&variant.variant);
                    let variant_has_fields = !variant.all_params().is_empty();
                    let pattern = if !variant_has_fields {
                        format!("{}::{}", enum_name, pascal)
                    } else {
                        // Destructure the fields referenced in this block (direct
                        // and nested), ignoring the rest of the variant.
                        let mut used: Vec<String> = Vec::new();
                        for p in parse_parameter_names_from_sql(&block.sql_content) {
                            let c = strip_input_suffix(&p);
                            if !used.contains(&c) {
                                used.push(c);
                            }
                        }
                        if used.is_empty() {
                            format!("{}::{} {{ .. }}", enum_name, pascal)
                        } else {
                            format!("{}::{} {{ {}, .. }}", enum_name, pascal, used.join(", "))
                        }
                    };
                    let arm = if group.required {
                        pattern
                    } else {
                        format!("Some({})", pattern)
                    };
                    body.push_str(&format!("    if let {} = &{} {{\n", arm, group.selector));
                    emit_choice_group_block_tokens(
                        body,
                        &inner,
                        "        ",
                        true,
                        &all_params,
                        type_info,
                    );
                    body.push_str("    }\n");
                } else if block.parameters.is_empty() {
                    // Additive block with no parameters: always included.
                    emit_choice_group_block_tokens(
                        body,
                        &inner,
                        "    ",
                        false,
                        &all_params,
                        type_info,
                    );
                } else {
                    // Additive block: gated by its first parameter's presence.
                    let gate = block.parameters[0].trim_end_matches('?');
                    body.push_str(&format!("    if {}.is_some() {{\n", gate));
                    emit_choice_group_block_tokens(
                        body,
                        &inner,
                        "        ",
                        false,
                        &all_params,
                        type_info,
                    );
                    body.push_str("    }\n");
                }
            }
        }
    }

    body.push_str("    let query = qb.build();\n\n");

    generate_query_execution(body, query, type_info, return_type);
    Ok(())
}

/// Generate function body for conditional (dynamic) SQL queries
/// A single token of a parsed SQL template (base SQL with `#{param}`
/// placeholders and `#[...]` conditional blocks preserved).
enum SqlToken {
    /// Literal SQL text to emit verbatim.
    Lit(String),
    /// A `#{param}` placeholder (name may retain a trailing `?`).
    Param(String),
    /// A `#[...]` conditional block with its inner tokens and the list of
    /// parameter names referenced inside it (in source order).
    Block {
        inner: Vec<SqlToken>,
        params: Vec<String>,
    },
}

/// Tokenize a base SQL template into an ordered sequence of literal, parameter
/// and conditional-block tokens. Preserves all literal characters (including
/// whitespace) exactly so the reconstructed SQL matches the source.
fn tokenize_base_sql(sql: &str) -> Vec<SqlToken> {
    use crate::types_extractor::parse_parameter_names_from_sql;

    let mut tokens = Vec::new();
    let mut lit = String::new();
    let mut chars = sql.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '#' {
            match chars.peek() {
                Some('[') => {
                    chars.next(); // consume '['
                    let mut inner = String::new();
                    let mut depth = 1;
                    while let Some(c) = chars.next() {
                        if c == '[' {
                            depth += 1;
                            inner.push(c);
                        } else if c == ']' {
                            depth -= 1;
                            if depth == 0 {
                                break;
                            }
                            inner.push(c);
                        } else {
                            inner.push(c);
                        }
                    }
                    if !lit.is_empty() {
                        tokens.push(SqlToken::Lit(std::mem::take(&mut lit)));
                    }
                    let params = parse_parameter_names_from_sql(&inner);
                    let inner_tokens = tokenize_base_sql(&inner);
                    tokens.push(SqlToken::Block {
                        inner: inner_tokens,
                        params,
                    });
                }
                Some('{') => {
                    chars.next(); // consume '{'
                    let mut name = String::new();
                    for c in chars.by_ref() {
                        if c == '}' {
                            break;
                        }
                        name.push(c);
                    }
                    if !lit.is_empty() {
                        tokens.push(SqlToken::Lit(std::mem::take(&mut lit)));
                    }
                    tokens.push(SqlToken::Param(name));
                }
                _ => lit.push(ch),
            }
        } else {
            lit.push(ch);
        }
    }

    if !lit.is_empty() {
        tokens.push(SqlToken::Lit(lit));
    }

    tokens
}

/// Produce a Rust raw string literal for `s`, preserving its contents exactly
/// (no re-indentation), choosing a `#` guard that does not collide with the
/// text.
fn raw_string_literal(s: &str) -> String {
    let mut n = 0;
    loop {
        let delim = "#".repeat(n);
        if !s.contains(&format!("\"{}", delim)) {
            return format!("r{d}\"{s}\"{d}", d = delim, s = s);
        }
        n += 1;
    }
}

/// Look up the input-type info for a parameter by its clean (suffix-stripped)
/// name, indexing positionally against the query's source-order parameters.
fn find_input_type<'a>(
    all_params: &[String],
    type_info: &'a QueryTypeInfo,
    clean: &str,
) -> Option<&'a InputParam> {
    all_params
        .iter()
        .position(|p| p.trim_end_matches('?') == clean)
        .and_then(|idx| type_info.input_types.get(idx))
}

/// Emit a single `qb.push_bind(...)` for one parameter, applying the JSON
/// serialization wrapper when the parameter maps to a custom type stored as
/// jsonb. `owner` is the expression that yields the value (e.g. `name`,
/// `params.name`, `new.name`, `name.as_ref().unwrap()`); `owner_is_ref` is
/// true when that expression already yields a reference (so no extra `&` is
/// added for the plain bind). All bound values flow through `push_bind`, never
/// string interpolation, so there is no SQL-injection surface.
fn emit_push_bind(
    body: &mut String,
    indent: &str,
    ti: &InputParam,
    owner: &str,
    owner_is_ref: bool,
    tmp: &str,
) {
    if ti.needs_json_wrapper {
        if ti.is_pg_array() {
            // For jsonb[] columns: serialize each element individually so that
            // NULL elements survive as SQL NULL rather than JSON null.
            body.push_str(&format!(
                "{i}let {t}_json: Vec<Option<serde_json::Value>> = {o}.iter().map(|el| el.as_ref().map(|v| serde_json::to_value(v)).transpose().map_err(|e| sqlx::Error::Encode(Box::new(e)))).collect::<Result<_, _>>()?;\n",
                i = indent, t = tmp, o = owner
            ));
            body.push_str(&format!(
                "{i}qb.push_bind({t}_json);\n",
                i = indent,
                t = tmp
            ));
        } else {
            body.push_str(&format!(
                "{i}qb.push_bind(serde_json::to_value(&{o}).map_err(|e| sqlx::Error::Encode(Box::new(e)))?);\n",
                i = indent, o = owner
            ));
        }
    } else {
        let amp = if owner_is_ref { "" } else { "&" };
        body.push_str(&format!(
            "{i}qb.push_bind({a}{o});\n",
            i = indent,
            a = amp,
            o = owner
        ));
    }
}

/// Emit a single `let query = query.bind(...)` for one static-path parameter,
/// applying the JSON serialization wrapper for custom (jsonb) types. `owner` is
/// the value expression (e.g. `name` or `params.name`) and `tmp` the base name
/// for any intermediate `_json` local. Mirrors `emit_push_bind` but targets the
/// `sqlx::query(...).bind()` API used by static queries (which keep raw `Option`
/// arguments, hence the extra optional-scalar case).
fn emit_static_bind(body: &mut String, ip: &InputParam, owner: &str, tmp: &str) {
    if ip.needs_json_wrapper {
        if ip.is_pg_array() {
            // For jsonb[] columns: serialize each element individually so NULL
            // elements survive as SQL NULL rather than JSON null.
            body.push_str(&format!(
                "    let {t}_json: Vec<Option<serde_json::Value>> = {o}.iter().map(|el| el.as_ref().map(|v| serde_json::to_value(v)).transpose().map_err(|e| sqlx::Error::Encode(Box::new(e)))).collect::<Result<_, _>>()?;\n",
                t = tmp, o = owner
            ));
            body.push_str(&format!("    let query = query.bind({t}_json);\n", t = tmp));
        } else if ip.is_optional {
            // Optional custom type: map through Option so None becomes SQL NULL
            // rather than a JSON null literal.
            body.push_str(&format!(
                "    let query = query.bind({o}.as_ref().map(|v| serde_json::to_value(v)).transpose().map_err(|e| sqlx::Error::Encode(Box::new(e)))?);\n",
                o = owner
            ));
        } else {
            // For custom types, serialize to JSON before binding.
            body.push_str(&format!(
                "    let query = query.bind(serde_json::to_value(&{o}).map_err(|e| sqlx::Error::Encode(Box::new(e)))?);\n",
                o = owner
            ));
        }
    } else if ip.rust_type() == "String" {
        // Bind Strings by reference to avoid moving the argument.
        body.push_str(&format!("    let query = query.bind(&{o});\n", o = owner));
    } else {
        body.push_str(&format!("    let query = query.bind({o});\n", o = owner));
    }
}

fn generate_conditional_function_body(
    body: &mut String,
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    parsed_sql: &crate::types_extractor::ParsedSql,
    return_type: &str,
    _defaults: &crate::DefaultsConfig,
) -> Result<()> {
    use crate::types_extractor::parse_parameter_names_from_sql;

    let use_conditional_diff = query.conditions_type.is_enabled();
    let use_structured_params = query.parameters_type.is_enabled() && !use_conditional_diff;
    // Parse all parameters from the original SQL to get their order and types.
    let all_params = parse_parameter_names_from_sql(&query.sql);

    // Tokenize the base SQL (with `#{param}` placeholders and `#[...]` blocks
    // preserved) and emit a sqlx::QueryBuilder. `push_bind` assigns `$N`
    // placeholders automatically in push order, so no manual renumbering or
    // inclusion tracking is required.
    let tokens = tokenize_base_sql(&parsed_sql.base_sql);

    body.push_str("    let mut qb = sqlx::QueryBuilder::<sqlx::Postgres>::new(\"\");\n");

    for token in &tokens {
        match token {
            SqlToken::Lit(s) => {
                if !s.is_empty() {
                    body.push_str(&format!("    qb.push({});\n", raw_string_literal(s)));
                }
            }
            SqlToken::Param(name) => {
                // Base (non-conditional) parameter: always present.
                let clean = name.trim_end_matches('?');
                let owner = if use_structured_params {
                    format!("params.{}", clean)
                } else {
                    clean.to_string()
                };
                if let Some(ti) = find_input_type(&all_params, type_info, clean) {
                    emit_push_bind(body, "    ", ti, &owner, false, clean);
                }
            }
            SqlToken::Block { inner, params } => {
                if params.is_empty() {
                    // No parameters gate this block; always include it.
                    for t in inner {
                        if let SqlToken::Lit(s) = t {
                            if !s.is_empty() {
                                body.push_str(&format!(
                                    "    qb.push({});\n",
                                    raw_string_literal(s)
                                ));
                            }
                        }
                    }
                    continue;
                }

                // The whole block is included/excluded based on its first
                // parameter; all of its parameters are then bound together.
                let gate = params[0].trim_end_matches('?');
                let condition = if use_conditional_diff {
                    format!("old.{g} != new.{g}", g = gate)
                } else if use_structured_params {
                    format!("params.{}.is_some()", gate)
                } else {
                    format!("{}.is_some()", gate)
                };
                body.push_str(&format!("    if {} {{\n", condition));

                for t in inner {
                    match t {
                        SqlToken::Lit(s) => {
                            if !s.is_empty() {
                                body.push_str(&format!(
                                    "        qb.push({});\n",
                                    raw_string_literal(s)
                                ));
                            }
                        }
                        SqlToken::Param(name) => {
                            let clean = name.trim_end_matches('?');
                            let (owner, owner_is_ref) = if use_conditional_diff {
                                (format!("new.{}", clean), false)
                            } else if use_structured_params {
                                (format!("params.{}.as_ref().unwrap()", clean), true)
                            } else {
                                (format!("{}.as_ref().unwrap()", clean), true)
                            };
                            if let Some(ti) = find_input_type(&all_params, type_info, clean) {
                                emit_push_bind(body, "        ", ti, &owner, owner_is_ref, clean);
                            }
                        }
                        // Nested conditional blocks are not produced for plain
                        // conditional queries (only the mixed choice path uses
                        // nesting), so there is nothing to emit here.
                        SqlToken::Block { .. } => {}
                    }
                }

                body.push_str("    }\n");
            }
        }
    }

    body.push_str("    let query = qb.build();\n\n");

    generate_query_execution(body, query, type_info, return_type);
    Ok(())
}
/// Generate the query execution part (common for both static and conditional queries)
fn generate_query_execution(
    body: &mut String,
    query: &QueryDefinition,
    type_info: &QueryTypeInfo,
    return_type: &str,
) {
    // Always use .map_err(Into::into) since both Error<C> and ErrorReadOnly have From<sqlx::Error>
    let map_err_suffix = ".map_err(Into::into)";

    if type_info.output_types.is_empty() {
        // For queries that don't return data (INSERT, UPDATE, DELETE)
        body.push_str("    query.execute(executor).await?;\n");
        body.push_str("    Ok(())\n");
    } else if type_info.output_types.len() == 1 && query.return_type.is_none() {
        // For queries that return a single column as a raw type (no explicit return_type)
        match query.expect {
            ExpectedResult::ExactlyOne => {
                body.push_str("    let row = query.fetch_one(executor).await?;\n");
                let value_extraction =
                    generate_sqlx_value_extraction(&type_info.output_types[0], 0);
                body.push_str(&format!("    Ok({})\n", value_extraction));
            }
            ExpectedResult::PossibleOne => {
                body.push_str("    let row = query.fetch_optional(executor).await?;\n");
                body.push_str("    match row {\n");
                body.push_str("        Some(row) => {\n");
                let value_extraction =
                    generate_sqlx_value_extraction(&type_info.output_types[0], 0);
                if type_info.output_types[0].is_nullable {
                    body.push_str(&format!("            Ok({})\n", value_extraction));
                } else {
                    body.push_str(&format!("            Ok(Some({}))\n", value_extraction));
                }
                body.push_str("        },\n");
                body.push_str("        None => Ok(None),\n");
                body.push_str("    }\n");
            }
            ExpectedResult::AtLeastOne => {
                body.push_str("    let rows = query.fetch_all(executor).await?;\n");
                body.push_str("    if rows.is_empty() {\n");
                body.push_str("        return Err(sqlx::Error::RowNotFound.into());\n");
                body.push_str("    }\n");
                body.push_str(
                    "    let result: Result<Vec<_>, sqlx::Error> = rows.iter().map(|row| {\n",
                );
                let value_extraction =
                    generate_sqlx_value_extraction(&type_info.output_types[0], 0);
                body.push_str(&format!("        Ok({})\n", value_extraction));
                body.push_str("    }).collect();\n");
                body.push_str(&format!("    result{}\n", map_err_suffix));
            }
            ExpectedResult::Multiple => {
                body.push_str("    let rows = query.fetch_all(executor).await?;\n");
                body.push_str(
                    "    let result: Result<Vec<_>, sqlx::Error> = rows.iter().map(|row| {\n",
                );
                let value_extraction =
                    generate_sqlx_value_extraction(&type_info.output_types[0], 0);
                body.push_str(&format!("        Ok({})\n", value_extraction));
                body.push_str("    }).collect();\n");
                body.push_str(&format!("    result{}\n", map_err_suffix));
            }
        }
    } else {
        // For queries that return multiple columns
        match query.expect {
            ExpectedResult::ExactlyOne => {
                body.push_str("    let row = query.fetch_one(executor).await?;\n");
                body.push_str("    let result: Result<_, sqlx::Error> = (|| {\n");
                let struct_creation =
                    generate_sqlx_struct_creation(return_type, &type_info.output_types);
                body.push_str(&format!("        Ok({})\n", struct_creation));
                body.push_str("    })();\n");
                body.push_str(&format!("    result{}\n", map_err_suffix));
            }
            ExpectedResult::PossibleOne => {
                body.push_str("    let row = query.fetch_optional(executor).await?;\n");
                body.push_str("    match row {\n");
                body.push_str("        Some(row) => {\n");
                body.push_str("            let result: Result<_, sqlx::Error> = (|| {\n");
                let struct_creation =
                    generate_sqlx_struct_creation(return_type, &type_info.output_types);
                body.push_str(&format!("                Ok({})\n", struct_creation));
                body.push_str("            })();\n");
                body.push_str(&format!("            result.map(Some){}\n", map_err_suffix));
                body.push_str("        },\n");
                body.push_str("        None => Ok(None),\n");
                body.push_str("    }\n");
            }
            ExpectedResult::AtLeastOne => {
                body.push_str("    let rows = query.fetch_all(executor).await?;\n");
                body.push_str("    if rows.is_empty() {\n");
                body.push_str("        return Err(sqlx::Error::RowNotFound.into());\n");
                body.push_str("    }\n");
                body.push_str(
                    "    let result: Result<Vec<_>, sqlx::Error> = rows.iter().map(|row| {\n",
                );
                let struct_creation =
                    generate_sqlx_struct_creation(return_type, &type_info.output_types);
                body.push_str(&format!("        Ok({})\n", struct_creation));
                body.push_str("    }).collect();\n");
                body.push_str(&format!("    result{}\n", map_err_suffix));
            }
            ExpectedResult::Multiple => {
                body.push_str("    let rows = query.fetch_all(executor).await?;\n");
                body.push_str(
                    "    let result: Result<Vec<_>, sqlx::Error> = rows.iter().map(|row| {\n",
                );
                let struct_creation =
                    generate_sqlx_struct_creation(return_type, &type_info.output_types);
                body.push_str(&format!("        Ok({})\n", struct_creation));
                body.push_str("    }).collect();\n");
                body.push_str(&format!("    result{}\n", map_err_suffix));
            }
        }
    }
}

/// Generate SQLx value extraction for a single column
fn generate_sqlx_value_extraction(output_col: &OutputColumn, _index: usize) -> String {
    let column_name = &output_col.pg_name;

    if output_col.needs_json_wrapper {
        // For custom types, we need to extract as serde_json::Value and then deserialize
        let inner_type = output_col.rust_type();
        if output_col.is_pg_array() {
            // For jsonb[] columns: extract as Vec<Option<serde_json::Value>>, deserialize each element
            // The inner_type is already Vec<Option<T>>, extract the element type T
            let element_type =
                if inner_type.starts_with("Vec<Option<") && inner_type.ends_with(">>") {
                    &inner_type[11..inner_type.len() - 2]
                } else if inner_type.starts_with("Vec<") && inner_type.ends_with(">") {
                    &inner_type[4..inner_type.len() - 1]
                } else {
                    inner_type
                };
            // Note: sqlx may return jsonb null as Some(Value::Null) rather than None,
            // so we filter through .and_then() to normalize both to None
            if output_col.is_nullable {
                format!(
                    "row.try_get::<Option<Vec<Option<serde_json::Value>>>, _>(\"{}\")?
            .map(|arr| arr.into_iter().map(|el| el.and_then(|v| if v.is_null() {{ None }} else {{ Some(v) }}).map(|v| serde_json::from_value::<{}>(v).map_err(|e| sqlx::Error::Decode(Box::new(e)))).transpose()).collect::<Result<Vec<_>, _>>())
            .transpose()?",
                    column_name, element_type
                )
            } else {
                format!(
                    "row.try_get::<Vec<Option<serde_json::Value>>, _>(\"{}\")?
            .into_iter().map(|el| el.and_then(|v| if v.is_null() {{ None }} else {{ Some(v) }}).map(|v| serde_json::from_value::<{}>(v).map_err(|e| sqlx::Error::Decode(Box::new(e)))).transpose()).collect::<Result<Vec<_>, _>>()?",
                    column_name, element_type
                )
            }
        } else if output_col.is_nullable {
            format!(
                "row.try_get::<Option<serde_json::Value>, _>(\"{}\")?
            .map(|v| serde_json::from_value::<{}>(v)
            .map_err(|e| sqlx::Error::Decode(Box::new(e))))
            .transpose()?",
                column_name, inner_type
            )
        } else {
            format!(
                "serde_json::from_value::<{}>(
            row.try_get::<serde_json::Value, _>(\"{}\")?)
            .map_err(|e| sqlx::Error::Decode(Box::new(e)))?",
                inner_type, column_name
            )
        }
    } else {
        // For standard types, extract directly
        if output_col.is_nullable {
            format!(
                "row.try_get::<Option<{}>, _>(\"{}\")?",
                output_col.rust_type(),
                column_name
            )
        } else {
            format!(
                "row.try_get::<{}, _>(\"{}\")?",
                output_col.rust_type(),
                column_name
            )
        }
    }
}

/// Generate SQLx struct creation code for multi-column results
fn generate_sqlx_struct_creation(struct_name: &str, output_types: &[OutputColumn]) -> String {
    let mut creation = format!("{} {{\n", struct_name);

    for (i, col) in output_types.iter().enumerate() {
        let value_extraction = generate_sqlx_value_extraction(col, i);
        creation.push_str(&format!(
            "        {}: {},\n",
            col.rust_name, value_extraction
        ));
    }

    creation.push_str("    }");
    creation
}

/// Validates that a referenced struct exists and has matching parameter fields
/// Returns Ok if validation passes, Err with a descriptive message if not
pub fn validate_struct_reference(
    struct_name: &str,
    query_params: &[String],
    query_param_types: &[InputParam],
    available_structs: &std::collections::HashMap<String, Vec<(String, String)>>,
    is_conditional_diff: bool,
) -> Result<()> {
    // Check if the struct exists
    let struct_fields = available_structs.get(struct_name).ok_or_else(|| {
        anyhow::anyhow!(
            "Referenced struct '{}' does not exist. Make sure it's defined by a previous query (either via parameters_type: true for params structs, or as a return type for multi-column queries)",
            struct_name
        )
    })?;

    // Build a map of query parameters for comparison
    let mut query_field_map: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();
    for (i, param_name) in query_params.iter().enumerate() {
        let clean_param = param_name.trim_end_matches('?');
        if let Some(param_type) = query_param_types.get(i) {
            let type_str = if param_type.is_nullable || param_type.is_optional {
                format!("Option<{}>", param_type.rust_type())
            } else {
                param_type.rust_type().to_string()
            };
            query_field_map.insert(clean_param.to_string(), type_str);
        }
    }

    // Check if all query parameters exist in the struct with matching types
    for (param_name, param_type) in &query_field_map {
        let struct_field = struct_fields
            .iter()
            .find(|(name, _)| name == param_name)
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "Query parameter '{}' not found in struct '{}'. Available fields: {}",
                    param_name,
                    struct_name,
                    struct_fields
                        .iter()
                        .map(|(n, _)| n.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })?;

        // For conditional diff, allow flexible type matching
        // The struct can have String while query has Option<String>, since we're comparing old vs new
        let types_match = if is_conditional_diff {
            // Check if types are compatible: exact match OR struct is non-nullable and query is nullable
            &struct_field.1 == param_type
                || (param_type.starts_with("Option<")
                    && param_type.ends_with(">")
                    && &struct_field.1 == &param_type[7..param_type.len() - 1])
        } else {
            // For non-conditional, require exact match
            &struct_field.1 == param_type
        };

        if !types_match {
            anyhow::bail!(
                "Type mismatch for parameter '{}' in struct '{}': expected '{}', but query requires '{}'",
                param_name,
                struct_name,
                struct_field.1,
                param_type
            );
        }
    }

    Ok(())
}

/// Generate code for a single module
pub fn generate_code_for_module(
    analyzed_queries: &[QueryDefinitionRuntime],
    module: &str,
    defaults: &crate::DefaultsConfig,
) -> Result<(String, Vec<String>)> {
    let mut generated_code = String::new();
    let mut warnings = Vec::new();

    // Add header comment
    generated_code
        .push_str("// This file was automatically generated by AutoModel. Do not edit manually.\n");
    generated_code.push_str("// @generated\n\n");

    // Filter queries for this module
    let module_queries: Vec<&QueryDefinitionRuntime> = analyzed_queries
        .iter()
        .filter(|q| q.module() == module)
        .collect();

    if module_queries.is_empty() {
        return Ok((generated_code, warnings));
    }

    // Collect warnings from performance analysis
    for analyzed in &module_queries {
        if let Some(perf) = &analyzed.performance_analysis {
            warnings.extend(perf.warnings.clone());
        }
    }

    // Check if any query has output types (needs Row trait for try_get method)
    let needs_row_import = module_queries
        .iter()
        .any(|q| !q.type_info.output_types.is_empty());

    if needs_row_import {
        generated_code.push_str("use sqlx::Row;\n\n");
    }

    // Enum and composite types are now generated by TypeSystem::codegen() into types/ directory.
    // No per-module inline enum/struct generation is needed.

    // Track generated structs for validation
    let mut generated_structs: std::collections::HashMap<String, Vec<(String, String)>> =
        std::collections::HashMap::new();

    // Process all queries for struct tracking and validation (same logic as before)
    for analyzed in &module_queries {
        let query = &analyzed.definition;
        let type_info = &analyzed.type_info;

        // Handle conditions_type struct
        if let Some(struct_name) = query.conditions_type.get_struct_name() {
            if !generated_structs.contains_key(struct_name) {
                let param_names = parse_parameter_names_from_sql(&query.sql);
                let mut fields = Vec::new();
                for (i, param_name) in param_names.iter().enumerate() {
                    if param_name.ends_with('?') {
                        let clean_param = param_name.trim_end_matches('?');
                        if let Some(param_type) = type_info.input_types.get(i) {
                            let type_str = if param_type.is_nullable {
                                format!("Option<{}>", param_type.rust_type())
                            } else {
                                param_type.rust_type().to_string()
                            };
                            if !fields.iter().any(|(name, _)| name == clean_param) {
                                fields.push((clean_param.to_string(), type_str));
                            }
                        }
                    }
                }
                generated_structs.insert(struct_name.to_string(), fields);
            } else {
                let param_names = parse_parameter_names_from_sql(&query.sql);
                let conditional_param_names: Vec<String> = param_names
                    .iter()
                    .filter(|p| p.ends_with('?'))
                    .map(|p| p.trim_end_matches('?').to_string())
                    .collect();
                let conditional_param_types: Vec<_> = param_names
                    .iter()
                    .enumerate()
                    .filter(|(_, p)| p.ends_with('?'))
                    .filter_map(|(i, _)| type_info.input_types.get(i))
                    .cloned()
                    .collect();

                validate_struct_reference(
                    struct_name,
                    &conditional_param_names,
                    &conditional_param_types,
                    &generated_structs,
                    true,
                )?;
            }
        } else if query.conditions_type.is_enabled() && type_info.parsed_sql.is_some() {
            let struct_name = format!("{}Params", to_pascal_case(&query.name));
            let param_names = parse_parameter_names_from_sql(&query.sql);
            let mut fields = Vec::new();
            for (i, param_name) in param_names.iter().enumerate() {
                if param_name.ends_with('?') {
                    let clean_param = param_name.trim_end_matches('?');
                    if let Some(param_type) = type_info.input_types.get(i) {
                        let type_str = if param_type.is_nullable {
                            format!("Option<{}>", param_type.rust_type())
                        } else {
                            param_type.rust_type().to_string()
                        };
                        if !fields.iter().any(|(name, _)| name == clean_param) {
                            fields.push((clean_param.to_string(), type_str));
                        }
                    }
                }
            }
            generated_structs.insert(struct_name, fields);
        }

        // Handle parameters_type struct
        if let Some(struct_name) = query.parameters_type.get_struct_name() {
            if !generated_structs.contains_key(struct_name) {
                let param_names = parse_parameter_names_from_sql(&query.sql);
                let mut fields = Vec::new();
                for (i, param_name) in param_names.iter().enumerate() {
                    let clean_param = param_name.trim_end_matches('?');
                    if let Some(param_type) = type_info.input_types.get(i) {
                        let type_str = if param_type.is_nullable || param_type.is_optional {
                            format!("Option<{}>", param_type.rust_type())
                        } else {
                            param_type.rust_type().to_string()
                        };
                        if !fields.iter().any(|(name, _)| name == clean_param) {
                            fields.push((clean_param.to_string(), type_str));
                        }
                    }
                }
                generated_structs.insert(struct_name.to_string(), fields);
            } else {
                let param_names = parse_parameter_names_from_sql(&query.sql);
                validate_struct_reference(
                    struct_name,
                    &param_names,
                    &type_info.input_types,
                    &generated_structs,
                    false,
                )?;
            }
        } else if query.parameters_type.is_enabled() {
            let struct_name = format!("{}Params", to_pascal_case(&query.name));
            let param_names = parse_parameter_names_from_sql(&query.sql);
            let mut fields = Vec::new();
            for (i, param_name) in param_names.iter().enumerate() {
                let clean_param = param_name.trim_end_matches('?');
                if let Some(param_type) = type_info.input_types.get(i) {
                    let type_str = if param_type.is_nullable || param_type.is_optional {
                        format!("Option<{}>", param_type.rust_type())
                    } else {
                        param_type.rust_type().to_string()
                    };
                    if !fields.iter().any(|(name, _)| name == clean_param) {
                        fields.push((clean_param.to_string(), type_str));
                    }
                }
            }
            generated_structs.insert(struct_name, fields);
        }

        // Track return type struct (if multiple columns OR explicit return_type configured)
        let should_track_struct = type_info.output_types.len() > 1 || query.return_type.is_some();

        if should_track_struct {
            let struct_name = if let Some(ref custom_name) = query.return_type {
                custom_name.to_string()
            } else {
                format!("{}Item", to_pascal_case(&query.name))
            };

            if generated_structs.contains_key(&struct_name) {
                // Validate existing struct matches
                let existing_fields = generated_structs.get(&struct_name).unwrap();
                let expected_fields: Vec<(String, String)> = type_info
                    .output_types
                    .iter()
                    .map(|ot| {
                        let type_str = if ot.is_nullable {
                            format!("Option<{}>", ot.rust_type())
                        } else {
                            ot.rust_type().to_string()
                        };
                        (ot.pg_name.clone(), type_str)
                    })
                    .collect();

                if existing_fields.len() != expected_fields.len() {
                    anyhow::bail!(
                        "Query '{}' return type '{}' field count mismatch",
                        query.name,
                        struct_name
                    );
                }

                for (expected_name, expected_type) in &expected_fields {
                    if let Some(existing) = existing_fields.iter().find(|(n, _)| n == expected_name)
                    {
                        if &existing.1 != expected_type {
                            anyhow::bail!(
                                "Query '{}' return type '{}' field '{}' type mismatch",
                                query.name,
                                struct_name,
                                expected_name
                            );
                        }
                    }
                }
            } else {
                let mut fields = Vec::new();
                for output_type in &type_info.output_types {
                    let type_str = if output_type.is_nullable {
                        format!("Option<{}>", output_type.rust_type())
                    } else {
                        output_type.rust_type().to_string()
                    };
                    fields.push((output_type.pg_name.clone(), type_str));
                }
                generated_structs.insert(struct_name, fields);
            }
        }
    }

    // Track constraint enums
    let mut generated_constraint_enums: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();

    for analyzed in &module_queries {
        let query = &analyzed.definition;
        let constraints = &analyzed.constraints;

        if let Some(ref enum_name) = query.error_type {
            let expected_constraints: Vec<String> =
                constraints.iter().map(|c| c.name.clone()).collect();

            if let Some(existing_constraints) = generated_constraint_enums.get(enum_name) {
                if existing_constraints.len() != expected_constraints.len() {
                    anyhow::bail!(
                        "Query '{}' error_type '{}' constraint count mismatch",
                        query.name,
                        enum_name
                    );
                }
                for expected_constraint in &expected_constraints {
                    if !existing_constraints.contains(expected_constraint) {
                        anyhow::bail!(
                            "Query '{}' error_type '{}' missing constraint '{}'",
                            query.name,
                            enum_name,
                            expected_constraint
                        );
                    }
                }
            } else {
                generated_constraint_enums.insert(enum_name.to_string(), expected_constraints);
            }
        } else if !constraints.is_empty() {
            let enum_name = format!("{}Constraints", to_pascal_case(&query.name));
            let expected_constraints: Vec<String> =
                constraints.iter().map(|c| c.name.clone()).collect();
            generated_constraint_enums.insert(enum_name, expected_constraints);
        }
    }

    // Generate functions
    let mut emitted_struct_names = std::collections::HashSet::new();
    for analyzed in &module_queries {
        let function_code = generate_function_code_without_enums(
            &analyzed.definition,
            &analyzed.type_info,
            &mut emitted_struct_names,
            &analyzed.constraints,
            &analyzed.performance_analysis,
            defaults,
        )?;
        generated_code.push_str(&function_code);
        generated_code.push('\n');
    }

    Ok((generated_code, warnings))
}
