//! Code generation for the application-level sharding runtime.
//!
//! When sharding is enabled (via `sharding.shard_key` in `automodel.yml`), this
//! module emits a self-contained `sharding.rs` into the generated output. The
//! generated code depends only on `sqlx` and `tokio` (both already required by
//! any AutoModel consumer) — it does NOT pull in the `automodel` codegen crate
//! at runtime.
//!
//! The emitted runtime is fully generic over the shard-key type `K`; only the
//! trait's default type parameter is substituted with the configured `key_type`
//! so that consumers can write `&impl ShardedExecutor` without a turbofish and
//! projects that shard on a non-`uuid` key are not forced to depend on `uuid`.

/// Generate the contents of the `sharding.rs` module for the given shard-key
/// Rust type (e.g. `uuid::Uuid`).
pub fn generate_sharding_runtime(key_type: &str) -> String {
    TEMPLATE.replace("{{KEY_TYPE}}", key_type)
}

const TEMPLATE: &str = r#"// This file was automatically generated by AutoModel. Do not edit manually.
// @generated

//! Application-level sharding runtime.
//!
//! Implement [`ShardStrategy`] to map a shard key to a shard index, then wrap
//! your per-shard [`sqlx::PgPool`]s in a [`PoolRouter`] and pass `&router` to the
//! generated query functions. For multi-statement transactions on a single
//! shard, obtain a [`ShardedExecutorTransaction`] via [`PoolRouter::begin`].

/// Failure modes specific to shard routing. These are surfaced through the
/// generated `Error`/`ErrorReadOnly` types as the `Sharding` variant.
#[derive(Debug)]
pub enum ShardError {
    /// Failed to acquire a connection (or begin a transaction) on the target shard.
    Acquire(sqlx::Error),
    /// The shard key passed to a query does not match the shard the surrounding
    /// transaction was pinned to.
    WrongShard,
    /// A batch (multi-row) operation contained rows targeting more than one shard.
    InconsistentBatch,
}

impl std::fmt::Display for ShardError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ShardError::Acquire(err) => write!(f, "failed to acquire shard connection: {}", err),
            ShardError::WrongShard => write!(
                f,
                "shard key does not match the shard the transaction was pinned to"
            ),
            ShardError::InconsistentBatch => write!(
                f,
                "all rows in a sharded batch must resolve to the same shard"
            ),
        }
    }
}

impl std::error::Error for ShardError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ShardError::Acquire(err) => Some(err),
            _ => None,
        }
    }
}

/// Maps a shard key to a shard index in `0..shard_count`.
///
/// The mapping may be asynchronous (e.g. a lookup table backed by a cache or
/// database). Implementations must return an index strictly less than
/// `shard_count`.
pub trait ShardStrategy<K> {
    fn shard_index(
        &self,
        key: &K,
        shard_count: usize,
    ) -> impl std::future::Future<Output = usize> + Send;
}

/// An executor that routes a single statement to the shard selected by a key.
///
/// Both the pooled router ([`PoolRouter`]) and a pinned transaction
/// ([`ShardedExecutorTransaction`]) implement this trait, so generated functions
/// accept either uniformly. `resolve` takes `&self`, preserving concurrent use of
/// a shared `&PoolRouter`.
pub trait ShardedExecutor<K = {{KEY_TYPE}}> {
    /// A connection handle for the resolved shard. Dereferences to a
    /// [`sqlx::PgConnection`], which the generated code runs the statement on.
    type Conn<'a>: std::ops::DerefMut<Target = sqlx::PgConnection> + Send
    where
        Self: 'a,
        K: 'a;

    /// Resolve the executor for the shard that owns `shard_key`.
    ///
    /// The `shard_key` borrow (`'k`) is independent of the returned connection's
    /// lifetime (`'a`): the key is only needed while resolving, so the returned
    /// [`Self::Conn`] never keeps the key (or a batch's backing storage) borrowed.
    fn resolve<'a, 'k>(
        &'a self,
        shard_key: &'k K,
    ) -> impl std::future::Future<Output = Result<Self::Conn<'a>, ShardError>> + Send
    where
        K: 'a;
}

/// Routes queries across a fixed set of per-shard connection pools using a
/// [`ShardStrategy`].
///
/// `resolve` takes `&self`, so the common case is to share a single
/// `&PoolRouter` (or an `Arc<PoolRouter>`) across tasks — no clone required.
/// Cloning is supported but is O(shard_count): it allocates a new pool `Vec` and
/// bumps each pool's `Arc` refcount (plus clones the strategy). It never opens
/// new connections. For a cheap, O(1) shared handle, wrap it in `Arc`.
#[derive(Clone)]
pub struct PoolRouter<K, S> {
    pools: Vec<sqlx::PgPool>,
    strategy: S,
    _marker: std::marker::PhantomData<fn(K)>,
}

impl<K, S> PoolRouter<K, S>
where
    K: Send + Sync,
    S: ShardStrategy<K> + Send + Sync,
{
    /// Create a router over the given per-shard pools. `pools[i]` is the pool for
    /// shard index `i`.
    pub fn new(pools: Vec<sqlx::PgPool>, strategy: S) -> Self {
        Self {
            pools,
            strategy,
            _marker: std::marker::PhantomData,
        }
    }

    /// The per-shard pools, indexed by shard index.
    pub fn pools(&self) -> &[sqlx::PgPool] {
        &self.pools
    }

    /// Begin a transaction on the shard that owns `key`, pinned to that key.
    ///
    /// The returned [`ShardedExecutorTransaction`] can be passed to generated
    /// functions; any query whose shard key differs from `key` fails with
    /// [`ShardError::WrongShard`].
    pub async fn begin(
        &self,
        key: K,
    ) -> Result<ShardedExecutorTransaction<'static, K>, ShardError> {
        let idx = self.strategy.shard_index(&key, self.pools.len()).await;
        let tx = self.pools[idx].begin().await.map_err(ShardError::Acquire)?;
        Ok(ShardedExecutorTransaction {
            key,
            tx: tokio::sync::Mutex::new(tx),
        })
    }
}

impl<K, S> ShardedExecutor<K> for PoolRouter<K, S>
where
    K: Send + Sync,
    S: ShardStrategy<K> + Send + Sync,
{
    type Conn<'a>
        = sqlx::pool::PoolConnection<sqlx::Postgres>
    where
        Self: 'a;

    fn resolve<'a, 'k>(
        &'a self,
        shard_key: &'k K,
    ) -> impl std::future::Future<Output = Result<Self::Conn<'a>, ShardError>> + Send
    where
        K: 'a,
    {
        async move {
            let idx = self
                .strategy
                .shard_index(shard_key, self.pools.len())
                .await;
            self.pools[idx].acquire().await.map_err(ShardError::Acquire)
        }
    }
}

/// A transaction pinned to a single shard, obtained via [`PoolRouter::begin`].
///
/// Implements [`ShardedExecutor`] so it can be passed to generated functions.
/// Every `resolve` verifies the query's shard key matches the pinned key.
pub struct ShardedExecutorTransaction<'t, K> {
    key: K,
    tx: tokio::sync::Mutex<sqlx::Transaction<'t, sqlx::Postgres>>,
}

impl<'t, K> ShardedExecutorTransaction<'t, K> {
    /// Commit the underlying transaction.
    pub async fn commit(self) -> Result<(), sqlx::Error> {
        self.tx.into_inner().commit().await
    }

    /// Roll the underlying transaction back.
    pub async fn rollback(self) -> Result<(), sqlx::Error> {
        self.tx.into_inner().rollback().await
    }
}

/// Exclusive guard over a pinned transaction's connection, handed out by
/// [`ShardedExecutorTransaction::resolve`].
pub struct TxGuard<'a, 't> {
    guard: tokio::sync::MutexGuard<'a, sqlx::Transaction<'t, sqlx::Postgres>>,
}

impl<'a, 't> std::ops::Deref for TxGuard<'a, 't> {
    type Target = sqlx::PgConnection;
    fn deref(&self) -> &sqlx::PgConnection {
        &**self.guard
    }
}

impl<'a, 't> std::ops::DerefMut for TxGuard<'a, 't> {
    fn deref_mut(&mut self) -> &mut sqlx::PgConnection {
        &mut **self.guard
    }
}

impl<'t, K> ShardedExecutor<K> for ShardedExecutorTransaction<'t, K>
where
    K: PartialEq + Send + Sync,
{
    type Conn<'a>
        = TxGuard<'a, 't>
    where
        Self: 'a;

    fn resolve<'a, 'k>(
        &'a self,
        shard_key: &'k K,
    ) -> impl std::future::Future<Output = Result<Self::Conn<'a>, ShardError>> + Send
    where
        K: 'a,
    {
        async move {
            if shard_key != &self.key {
                return Err(ShardError::WrongShard);
            }
            Ok(TxGuard {
                guard: self.tx.lock().await,
            })
        }
    }
}
"#;
